stages:
  preprocess_train:
    cmd: python src\preprocess_data.py -s 1 -i data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_08_32_338904.csv data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_15_43_988750.csv data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_22_17_675082.csv
  preprocess_test:
    cmd: python src\preprocess_data.py -s 1 -i data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_08_32_338904.csv data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_15_43_988750.csv data/raw/cian_flat_sale_1_50_moskva_26_Apr_2024_14_22_17_675082.csv
  train_model:
    cmd: python src\train_model.py -m models/linear_regression_v01.joblib
  test_model:
    cmd: python src\test_model.py -m models/linear_regression_v01.joblib
